[tool.briefcase]
project_name = "gweatherrouting-beeware"
bundle = "com.gweatherrouting"
version = "0.0.1"
url = "https://gweatherrouting.com/gweatherrouting-beeware"
license = "MIT license"
author = 'Jane Developer'
author_email = "jane@gweatherrouting.com"

[tool.briefcase.app.gweatherrouting-beeware]
formal_name = "gwr"
description = "My first application"
icon = "src/gweatherrouting_beeware/resources/gweatherrouting-beeware"
sources = ['src/gweatherrouting_beeware']
requires = []


[tool.briefcase.app.gweatherrouting-beeware.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.gweatherrouting-beeware.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.gweatherrouting-beeware.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.gweatherrouting-beeware.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.gweatherrouting-beeware.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
