on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: AppImage generation
    steps:
      - uses: actions/checkout@v4
      - name: Install Ubuntu Dependencies
        run: |
            chmod +x .github/workflows/script/ubuntu_dep_eccodes_bin.sh
            .github/workflows/script/ubuntu_dep_eccodes_bin.sh
      - name: Install Python
        run: |
            chmod +x .github/workflows/script/python_dep.sh
            .github/workflows/script/python_dep.sh

