name: Build AppImage
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: AppImage generation
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ubuntu Dependencies (ecCodes by binary)
        run: |
            chmod +x .github/workflows/script/ubuntu_dep_eccodes_bin.sh
            .github/workflows/script/ubuntu_dep_eccodes_bin.sh

      - name: Install Python Dependencies
        run: |
            chmod +x .github/workflows/script/python_dep.sh
            .github/workflows/script/python_dep.sh
            pip install pyinstaller
      - name: Instal gww
        run: pip install .

      - name: Generate AppImage
        run: |
            cd appimage
            bash appimagegen.sh -y

      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
            name: Upload AppImage
            path: ${{ github.workspace }}/**/*.AppImage
