name: Flatpak

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-46
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Download wheels
      run: bash .github/workflows/scripts/flatpak-dep.sh 46

    - name: Setup Flatpak builder
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: GWeatherRouting-linux-x86_64.flatpak
        manifest-path: flatpak/org.gweatherrouting.app.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Upload Flatpak
      uses: actions/upload-artifact@v4
      with:
        name: GWeatherRouting-linux-x86_64.flatpak
        path: flatpak